services:
  api:
    build:
      context: .
    environment:
      AWS_REGION: ${AWS_REGION:-us-east-1}
      CARDOCS_DYNAMODB_TABLE: ${CARDOCS_DYNAMODB_TABLE:-cardocs-develop}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID:-}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY:-}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN:-}
      CARDOCS_API_KEY: ${CARDOCS_API_KEY:-}
      CARSXE_API_KEY: ${CARSXE_API_KEY:-}
      PORT: 8080
    ports:
      - "8080:8080"
