package com.cardocs.api.audit;

public enum AuditAction {
    USER_CREATED,
    USER_DELETED,
    VEHICLE_CREATED,
    VEHICLE_UPDATED,
    DOCUMENT_UPLOADED,
    DOCUMENT_DELETED,
    OCR_PROCESSED,
    MAINTENANCE_CREATED,
    REMINDER_CREATED,
    SHARE_LINK_CREATED,
    SHARE_LINK_ACCESSED,
    SHARE_LINK_REVOKED,
    DATA_EXPORTED,
    CONSENT_GRANTED,
    CONSENT_REVOKED,
    ADMIN_ACTION
}
